[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@nestjs/microservices", "@grpc/grpc-js", "@grpc/proto-loader", "cache-manager", "firebase", "firebase-admin"]
  included_files = ["dist/apps/api/**/*.graphql", "netlify/functions/*.js", "netlify/functions/package.json", "netlify/functions/package-lock.json"]
  excluded_files = ["netlify/functions/*.ts", "netlify/functions/**/*.ts"]
  
# Configuração específica para funções individuais
[functions.clickup-proxy]
  included_files = ["netlify/functions/clickup-proxy.js"]
  excluded_files = ["netlify/functions/clickup-proxy.ts"]

[functions.get-clickup-config]
  included_files = ["netlify/functions/get-clickup-config.js"]
  excluded_files = ["netlify/functions/get-clickup-config.ts"]

[functions.delete-webhook]
  included_files = ["netlify/functions/delete-webhook.js"]
  excluded_files = ["netlify/functions/delete-webhook.ts"]
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/clickup/webhook"
  to = "/.netlify/functions/clickup-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhooks"
  to = "/.netlify/functions/list-webhooks"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook-proxy"
  to = "/.netlify/functions/webhook-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/clickup/proxy"
  to = "/.netlify/functions/clickup-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/clickup/config"
  to = "/.netlify/functions/get-clickup-config"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/delete/*"
  to = "/.netlify/functions/delete-webhook?id=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/clickup/status"
  to = "/.netlify/functions/update-clickup-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/*"
  to = "https://webhook.sistemaneurosaber.com.br/webhook/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From-Netlify = "true"
    Forward-Auth = "true"
    Forward-Host = "true"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-API-Key, Content-Type, Accept, X-Requested-With, Authorization"
    Cache-Control = "no-cache"