[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/clickup/webhook"
  to = "/.netlify/functions/clickup-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhooks"
  to = "/.netlify/functions/list-webhooks"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook-proxy"
  to = "/.netlify/functions/webhook-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/*"
  to = "https://webhook.sistemaneurosaber.com.br/webhook/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From-Netlify = "true"
    Forward-Auth = "true"
    Forward-Host = "true"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-API-Key, Content-Type, Accept, X-Requested-With, Authorization"
    Cache-Control = "no-cache"

[build.environment]
  NODE_VERSION = "18"